# Use the official Node.js image
FROM node:16.18.0

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the server listens on
EXPOSE 9090

# Command to run the server
CMD ["node", "server.js"]
