apiVersion: v1
kind: Service
metadata:
  name: test-timeout-thrift-server-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
spec:
  type: LoadBalancer
  selector:
    app: test-timeout-thrift-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
