apiVersion: v1
kind: Service
metadata:
  name: test-timeout-thrift-server-svc
spec:
  type: ClusterIP
  selector:
    app: test-timeout-thrift-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
